replace print statements with logging
automata-tech/pyUSBtin pull request #1
Opened 2020-08-25 15:31 UTC by IsaacHook

allows us to remove output of print statements from the console.  cleaner interface for operators

2020-08-26 12:14 UTC, LouisBrunner requested changes
I don't think there is a point in changing the examples, the rest looks good.

2020-08-26 12:14 UTC, LouisBrunner commented
@IsaacHook Any timeline towards getting this merged upstream?

2020-10-21 14:15 UTC, IsaacHook commented
removed logging from examples

2020-10-21 14:22 UTC, LouisBrunner approved these changes

2020-10-21 14:26 UTC, merged